spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: lb://P2P-AUTH-SERVICE
              predicates:
                - Path=/api/v1/auth/**

            - id: user-service
              uri: lb://P2P-USER-SERVICE
              predicates:
                - Path=/api/v1/users/**

            - id: loan-service
              uri: lb://P2P-LOAN-SERVICE
              predicates:
                - Path=/api/v1/loan/**
